### PR TITLE
HPC2020 architecture files

### PR DESCRIPTION
**Pull request by reuterbal**
This adds arch files for GNU 9.3.0, GNU 11.2.0 and Intel 2021.4.0 on Atos HPC, and removes the obsolete TEMS architecture files.

Note:
- GNU 11 builds with MPI enabled fail without `-fallow-argument-mismatch`. This is terrible but might require switching from `#include mpif.h` to `use mpi_f08`.
- CLAW/OMNI does not seem to compile with GNU 11 (failing on duplicate symbols somehow)

Very rough performance results, with GNU11 doing surprisingly well (using NPROMA=64 for single precision runs):
```
export OMP_NUM_THREADS=64
OMP_PLACES="{$(seq -s '},{' 0 $(($OMP_NUM_THREADS-1)) )}" srun -q np --ntasks=1 --hint=nomultithread --cpus-per-task=$OMP_NUM_THREADS ./bin/dwarf-cloudsc-fortran $OMP_NUM_THREADS 163840 32

GNU 11.2.0 
- dp: 73.252 GFlop/s
- sp: 96.214 GFlop/s

GNU 9.3.0
- dp: 66.945 GFlop/s
- sp: 87.330 GFlop/s

Intel 2021.4.0
- dp: 66.866 GFlop/s
- sp: 77.242 GFlop/s

----

export OMP_NUM_THREADS=8
OMP_PLACES="cores" srun -q np --ntasks=$(( 64 / $OMP_NUM_THREADS )) --hint=nomultithread --cpus-per-task=$OMP_NUM_THREADS ./bin/dwarf-cloudsc-fortran $OMP_NUM_THREADS 163840 32

GNU 11.2.0 
- dp: 73.961 GFlop/s
- sp: 97.464 GFlop/s

GNU 9.3.0
- dp: 70.608 GFlop/s
- sp: 89.142 GFlop/s

Intel 2021.4.0
- dp: 70.476 GFlop/s
- sp: 79.282 GFlop/s
```

Deviations from Leap42/GNU 7.3.0 reference results are negligible for GNU builds (CLOUDSC's validation module doesn't even flag them with `!!!!`) and reasonably small for Intel builds.

### CODE REVIEW

**Comment by mlange05** [comment]
Ok, many apologies for the delay in reviewing this! This is really great and much needed!

I've gone through the arches and gotten similar results on all stacks, and I'm getting similar results to the ones demo'd here.

One final request though: Could you please add the arches and install instructions to the README, including the benchmark invocation line? Otherwise GTG.

**Review by mlange05 — CHANGES_REQUESTED** [review]
All very good! Only needs a quick README update and then GTG!

**Comment by FussyDuck** [comment]
[CLA assistant check](http://claassistant.ecmwf.int:80/ecmwf-ifs/dwarf-p-cloudsc?pullRequest=10) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](http://claassistant.ecmwf.int:80/ecmwf-ifs/dwarf-p-cloudsc?pullRequest=10) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](http://claassistant.ecmwf.int:80/check/ecmwf-ifs/dwarf-p-cloudsc?pullRequest=10) it.</sub>

**Comment by reuterbal** [comment]
Thanks for looking throught this! README updated, repurposing the existing (TEMS) bits from Olivier in a dedicated subsection.

**Review by mlange05 — APPROVED** [review]

**Pull request merged**
