### PR TITLE
Remove obsolete architectures, add march=znver2 option to gnu 

### PR DESCRIPTION
**Pull request by piotrows**
Deleted: Volta and XC40 arch and toolchain files. Gnu 11.2 arch updated with march=znver2 flag.
Performance study (selected vars) for release compilation and usual 64-threads submit

GNU znver2:
1 x 64 163840 163840 5120 32 -1 : 184 110979 889089 : TOTAL
Variable Dim AbsMaxErr AvgAbsErr/GP MaxRelErr-%
PCOVPTOT 2D3 0.2442490654175E-14 0.1442063258898E-14 0.5411442734520E-14
PFHPSN 2D3 0.7922551503725E-12 0.1452534394539E-11 0.2959350064515E-12 !!!!
TENDENCY_LOC%A 0.1631724269591E-16 0.2435464247654E-17 0.5335437305900E-12 !!!!
TENDENCY_LOC%T 0.5283368008499E-17 0.3296453892552E-17 0.1483380884237E-11 !!!!

Intel :

1 x 64 163840 163840 5120 32 -1 : 200 101822 815729 : TOTAL
Variable Dim AbsMaxErr AvgAbsErr/GP MaxRelErr-%
PCOVPTOT 2D3 0.1998401444325E-14 0.1009695290973E-14 0.3788951845695E-14
PFHPSN 2D3 0.1918465386552E-12 0.6828380140871E-12 0.1391193715371E-12
TENDENCY_LOC%A 0.1847378857962E-16 0.1660510467175E-17 0.3637725128560E-12 !!!!
TENDENCY_LOC%T 0.4450311104874E-17 0.1890424463654E-17 0.8506776080851E-12 !!!!

### CODE REVIEW

**Comment by mlange05** [comment]
Generally I have no objections to this, but I could not replicate the performance numbers quoted. Using the single-socket instructions form the README I'm getting around ~70GF/s for GNU-11 and ~85GF/s for Intel 21.4. Not sure what I'm missing here?

**Review by mlange05 — COMMENTED** [review]
In general this looks good. However, since we're now removing the `volta` arch files, could you please replace all mentions of them with the `hcp2020` equivalent in the README? Should be GTG once that is done. 

I've also left a comment regarding the performance claims, as I could not replicate the results from the description. I'm sure I'm just missing something, and would like to figure this out - but this is not a showstopper.

**Comment by piotrows** [comment]
> Generally I have no objections to this, but I could not replicate the performance numbers quoted. Using the single-socket instructions form the README I'm getting around ~70GF/s for GNU-11 and ~85GF/s for Intel 21.4. Not sure what I'm missing here?

Ok, so it is:
[napz@ac6-102 dwarf-p-cloudsc-arch]$ git status
On branch napz-zenver2-gnu
Your branch is up to date with 'origin/napz-zenver2-gnu'.

[napz@ac6-102 dwarf-p-cloudsc-arch]$ git remote show origin
* remote origin
  Fetch URL: git@github.com:ecmwf-ifs/dwarf-p-cloudsc.git
  
  [napz@ac6-102 dwarf-p-cloudsc-arch]$ ./cloudsc-bundle create
  [napz@ac6-102 dwarf-p-cloudsc-arch]$ ./cloudsc-bundle build --clean --build-type=release --arch=./arch/ecmwf/hpc2020/gnu/11.2.0/
  [napz@ac6-102 dwarf-p-cloudsc-arch]$ export OMP_NUM_THREADS=64
  [napz@ac6-102 dwarf-p-cloudsc-arch]$ OMP_PLACES="{$(seq -s '},{' 0 $(($OMP_NUM_THREADS-1)) )}" srun -q np --ntasks=1 --hint=nomultithread --cpus-per-task=$OMP_NUM_THREADS --pty /bin/bash
srun: job 31767253 queued and waiting for resources
srun: job 31767253 has been allocated resources
[napz@ac4-3056 dwarf-p-cloudsc-arch]$ cd build/
[napz@ac4-3056 build]$ ./bin/dwarf-cloudsc-fortran $OMP_NUM_THREADS 163840 32
....
   1 x  64    163840    163840      5120        32   -1 :        183    111196    890832 : TOTAL

**Comment by piotrows** [comment]
> In general this looks good. However, since we're now removing the `volta` arch files, could you please replace all mentions of them with the `hcp2020` equivalent in the README? Should be GTG once that is done.
> 
Good point, done. Running grep, I'am also seeing:
/home/napz/dwarf-p-cloudsc-arch/benchmark/arch/volta/nvhpc/22.3
Not sure about the purpose, shall we remove it as well ?

**Comment by mlange05** [comment]
> > In general this looks good. However, since we're now removing the `volta` arch files, could you please replace all mentions of them with the `hcp2020` equivalent in the README? Should be GTG once that is done.
> 
> @mlange05 Good point, done. Running grep, I'am also seeing: /home/napz/dwarf-p-cloudsc-arch/benchmark/arch/volta/nvhpc/22.3 Not sure about the purpose, shall we remove it as well ?

These are the benchmark configuration files for the JUBE setup; and yes, they can be removed as well. Thanks

**Review by mlange05 — APPROVED** [review]
All looking good not. GTG once CI is happy.

**Pull request merged**
